import './globals.css'
import 'highlight.js/styles/atom-one-dark.css'
import { Inter } from 'next/font/google'
import StoreProvider from './StoreProvider'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'yinpeng | 博客',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen w-screen overflow-hidden flex`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
